const placeHolderData = {
    myData: {
        id: 100,
        profileImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
        firstName: "John",
        lastName: "Doe",
        email: "johndoe@example.com",
        password: "BadPassword123",
        pronouns: "He/Him",
        major: "Sociology",
        gradYear: "2026",
        userBio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        fbURL: "https://www.facebook.com/",
        igURL: "https://www.instagram.com/",
        scURL: "https://www.snapchat.com/en-US",
        courses: [{
            id: 0,
            courseListing: "COMPSCI 61A",
            courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
            classNumber: "13234",
            classDis: "105",
            classLab: "123",
        }, {
            id: 1,
            courseListing: "EECS 16A",
            courseFullName: "Designing Information Devices and Systems",
            classNumber: "1",
            classDis: "105",
            classLab: "123",
        }, {
            id: 2,
            courseListing: "COMPSCI 61B",
            courseFullName: "Algorithms",
            classNumber: "13234",
            classDis: "1",
            classLab: "123",
        }, {
            id: 3,
            courseListing: "ANTHRO 2AC",
            courseFullName: "Introduction to Archaeology",
            classNumber: "13234",
            classDis: "105",
            classLab: "1",
        }, {
            id: 4,
            courseListing: "COMPSCI 61A",
            courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
            classNumber: "13234",
            classDis: "105",
            classLab: "123",
        }, {
            id: 5,
            courseListing: "COMPSCI 61A",
            courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
            classNumber: "13234",
            classDis: "105",
            classLab: "123",
        }, {
            id: 6,
            courseListing: "COMPSCI 61A",
            courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
            classNumber: "13234",
            classDis: "105",
            classLab: "123",
        }, {
            id: 7,
            courseListing: "COMPSCI 61A",
            courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
            classNumber: "13234",
            classDis: "105",
            classLab: "123",
        }, {
            id: 8,
            courseListing: "COMPSCI 61A",
            courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
            classNumber: "13234",
            classDis: "105",
            classLab: "123",
        }, {
            id: 9,
            courseListing: "COMPSCI 61A",
            courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
            classNumber: "13234",
            classDis: "105",
            classLab: "123",
        }]
    },
    otherData: [
        {
            id: 101,
            profileImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
            firstName: "Jenny",
            lastName: "Doe",
            email: "johndoe@example.com",
            password: "BadPassword123",
            pronouns: "He/Him",
            major: "Sociology",
            gradYear: "2026",
            userBio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            fbURL: "https://www.facebook.com/",
            igURL: "https://www.instagram.com/",
            scURL: "https://www.snapchat.com/en-US",
            courses: [{
                id: 0,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 1,
                courseListing: "EECS 16A",
                courseFullName: "Designing Information Devices and Systems",
                classNumber: "1",
                classDis: "105",
                classLab: "123",
            }, {
                id: 2,
                courseListing: "COMPSCI 61B",
                courseFullName: "Algorithms",
                classNumber: "13234",
                classDis: "1",
                classLab: "123",
            }, {
                id: 3,
                courseListing: "ANTHRO 2AC",
                courseFullName: "Introduction to Archaeology",
                classNumber: "13234",
                classDis: "105",
                classLab: "1",
            }, {
                id: 4,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 5,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 6,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 7,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 8,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 9,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }]
        },
        {
            id: 102,
            profileImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
            firstName: "Kiki",
            lastName: "Doe",
            email: "johndoe@example.com",
            password: "BadPassword123",
            pronouns: "He/Him",
            major: "Sociology",
            gradYear: "2026",
            userBio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            fbURL: "https://www.facebook.com/",
            igURL: "https://www.instagram.com/",
            scURL: "https://www.snapchat.com/en-US",
            courses: [{
                id: 0,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 1,
                courseListing: "EECS 16A",
                courseFullName: "Designing Information Devices and Systems",
                classNumber: "1",
                classDis: "105",
                classLab: "123",
            }, {
                id: 2,
                courseListing: "COMPSCI 61B",
                courseFullName: "Algorithms",
                classNumber: "13234",
                classDis: "1",
                classLab: "123",
            }, {
                id: 3,
                courseListing: "ANTHRO 2AC",
                courseFullName: "Introduction to Archaeology",
                classNumber: "13234",
                classDis: "105",
                classLab: "1",
            }, {
                id: 4,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 5,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 6,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 7,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 8,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 9,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }]
        },
        {
            id: 103,
            profileImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
            firstName: "Penny",
            lastName: "Doe",
            email: "johndoe@example.com",
            password: "BadPassword123",
            pronouns: "He/Him",
            major: "Sociology",
            gradYear: "2026",
            userBio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            fbURL: "https://www.facebook.com/",
            igURL: "https://www.instagram.com/",
            scURL: "https://www.snapchat.com/en-US",
            courses: [{
                id: 0,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 1,
                courseListing: "EECS 16A",
                courseFullName: "Designing Information Devices and Systems",
                classNumber: "1",
                classDis: "105",
                classLab: "123",
            }, {
                id: 2,
                courseListing: "COMPSCI 61B",
                courseFullName: "Algorithms",
                classNumber: "13234",
                classDis: "1",
                classLab: "123",
            }, {
                id: 3,
                courseListing: "ANTHRO 2AC",
                courseFullName: "Introduction to Archaeology",
                classNumber: "13234",
                classDis: "105",
                classLab: "1",
            }, {
                id: 4,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 5,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 6,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 7,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 8,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 9,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }]
        },
        {
            id: 104,
            profileImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
            firstName: "Polka",
            lastName: "Doe",
            email: "johndoe@example.com",
            password: "BadPassword123",
            pronouns: "He/Him",
            major: "Sociology",
            gradYear: "2026",
            userBio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            fbURL: "https://www.facebook.com/",
            igURL: "https://www.instagram.com/",
            scURL: "https://www.snapchat.com/en-US",
            courses: [{
                id: 0,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 1,
                courseListing: "EECS 16A",
                courseFullName: "Designing Information Devices and Systems",
                classNumber: "1",
                classDis: "105",
                classLab: "123",
            }, {
                id: 2,
                courseListing: "COMPSCI 61B",
                courseFullName: "Algorithms",
                classNumber: "13234",
                classDis: "1",
                classLab: "123",
            }, {
                id: 3,
                courseListing: "ANTHRO 2AC",
                courseFullName: "Introduction to Archaeology",
                classNumber: "13234",
                classDis: "105",
                classLab: "1",
            }, {
                id: 4,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 5,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 6,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 7,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 8,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 9,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }]
        },
        {
            id: 105,
            profileImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
            firstName: "David",
            lastName: "Doe",
            email: "johndoe@example.com",
            password: "BadPassword123",
            pronouns: "He/Him",
            major: "Sociology",
            gradYear: "2026",
            userBio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            fbURL: "https://www.facebook.com/",
            igURL: "https://www.instagram.com/",
            scURL: "https://www.snapchat.com/en-US",
            courses: [{
                id: 0,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 1,
                courseListing: "EECS 16A",
                courseFullName: "Designing Information Devices and Systems",
                classNumber: "1",
                classDis: "105",
                classLab: "123",
            }, {
                id: 2,
                courseListing: "COMPSCI 61B",
                courseFullName: "Algorithms",
                classNumber: "13234",
                classDis: "1",
                classLab: "123",
            }, {
                id: 3,
                courseListing: "ANTHRO 2AC",
                courseFullName: "Introduction to Archaeology",
                classNumber: "13234",
                classDis: "105",
                classLab: "1",
            }, {
                id: 4,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 5,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 6,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 7,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 8,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 9,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }]
        },
        {
            id: 106,
            profileImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
            firstName: "Yasha",
            lastName: "Doe",
            email: "johndoe@example.com",
            password: "BadPassword123",
            pronouns: "He/Him",
            major: "Sociology",
            gradYear: "2026",
            userBio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            fbURL: "https://www.facebook.com/",
            igURL: "https://www.instagram.com/",
            scURL: "https://www.snapchat.com/en-US",
            courses: [{
                id: 0,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 1,
                courseListing: "EECS 16A",
                courseFullName: "Designing Information Devices and Systems",
                classNumber: "1",
                classDis: "105",
                classLab: "123",
            }, {
                id: 2,
                courseListing: "COMPSCI 61B",
                courseFullName: "Algorithms",
                classNumber: "13234",
                classDis: "1",
                classLab: "123",
            }, {
                id: 3,
                courseListing: "ANTHRO 2AC",
                courseFullName: "Introduction to Archaeology",
                classNumber: "13234",
                classDis: "105",
                classLab: "1",
            }, {
                id: 4,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 5,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 6,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 7,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 8,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 9,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }]
        },
        {
            id: 107,
            profileImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
            firstName: "Meghan",
            lastName: "Doe",
            email: "johndoe@example.com",
            password: "BadPassword123",
            pronouns: "He/Him",
            major: "Sociology",
            gradYear: "2026",
            userBio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            fbURL: "https://www.facebook.com/",
            igURL: "https://www.instagram.com/",
            scURL: "https://www.snapchat.com/en-US",
            courses: [{
                id: 0,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 1,
                courseListing: "EECS 16A",
                courseFullName: "Designing Information Devices and Systems",
                classNumber: "1",
                classDis: "105",
                classLab: "123",
            }, {
                id: 2,
                courseListing: "COMPSCI 61B",
                courseFullName: "Algorithms",
                classNumber: "13234",
                classDis: "1",
                classLab: "123",
            }, {
                id: 3,
                courseListing: "ANTHRO 2AC",
                courseFullName: "Introduction to Archaeology",
                classNumber: "13234",
                classDis: "105",
                classLab: "1",
            }, {
                id: 4,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 5,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 6,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 7,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 8,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 9,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }]
        },
        {
            id: 108,
            profileImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
            firstName: "Thomas",
            lastName: "Doe",
            email: "johndoe@example.com",
            password: "BadPassword123",
            pronouns: "He/Him",
            major: "Sociology",
            gradYear: "2026",
            userBio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            fbURL: "https://www.facebook.com/",
            igURL: "https://www.instagram.com/",
            scURL: "https://www.snapchat.com/en-US",
            courses: [{
                id: 0,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 1,
                courseListing: "EECS 16A",
                courseFullName: "Designing Information Devices and Systems",
                classNumber: "1",
                classDis: "105",
                classLab: "123",
            }, {
                id: 2,
                courseListing: "COMPSCI 61B",
                courseFullName: "Algorithms",
                classNumber: "13234",
                classDis: "1",
                classLab: "123",
            }, {
                id: 3,
                courseListing: "ANTHRO 2AC",
                courseFullName: "Introduction to Archaeology",
                classNumber: "13234",
                classDis: "105",
                classLab: "1",
            }, {
                id: 4,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 5,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 6,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 7,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 8,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 9,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }]
        },
        {
            id: 109,
            profileImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
            firstName: "Jeffrey",
            lastName: "Doe",
            email: "johndoe@example.com",
            password: "BadPassword123",
            pronouns: "He/Him",
            major: "Sociology",
            gradYear: "2026",
            userBio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            fbURL: "https://www.facebook.com/",
            igURL: "https://www.instagram.com/",
            scURL: "https://www.snapchat.com/en-US",
            courses: [{
                id: 0,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 1,
                courseListing: "EECS 16A",
                courseFullName: "Designing Information Devices and Systems",
                classNumber: "1",
                classDis: "105",
                classLab: "123",
            }, {
                id: 2,
                courseListing: "COMPSCI 61B",
                courseFullName: "Algorithms",
                classNumber: "13234",
                classDis: "1",
                classLab: "123",
            }, {
                id: 3,
                courseListing: "ANTHRO 2AC",
                courseFullName: "Introduction to Archaeology",
                classNumber: "13234",
                classDis: "105",
                classLab: "1",
            }, {
                id: 4,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 5,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 6,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 7,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 8,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 9,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }]
        },
        {
            id: 110,
            profileImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
            firstName: "Tyson",
            lastName: "Doe",
            email: "johndoe@example.com",
            password: "BadPassword123",
            pronouns: "He/Him",
            major: "Sociology",
            gradYear: "2026",
            userBio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            fbURL: "https://www.facebook.com/",
            igURL: "https://www.instagram.com/",
            scURL: "https://www.snapchat.com/en-US",
            courses: [{
                id: 0,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 1,
                courseListing: "EECS 16A",
                courseFullName: "Designing Information Devices and Systems",
                classNumber: "1",
                classDis: "105",
                classLab: "123",
            }, {
                id: 2,
                courseListing: "COMPSCI 61B",
                courseFullName: "Algorithms",
                classNumber: "13234",
                classDis: "1",
                classLab: "123",
            }, {
                id: 3,
                courseListing: "ANTHRO 2AC",
                courseFullName: "Introduction to Archaeology",
                classNumber: "13234",
                classDis: "105",
                classLab: "1",
            }, {
                id: 4,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 5,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 6,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 7,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 8,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 9,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }]
        },
        {
            id: 111,
            profileImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
            firstName: "Robert",
            lastName: "Doe",
            email: "johndoe@example.com",
            password: "BadPassword123",
            pronouns: "He/Him",
            major: "Sociology",
            gradYear: "2026",
            userBio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            fbURL: "https://www.facebook.com/",
            igURL: "https://www.instagram.com/",
            scURL: "https://www.snapchat.com/en-US",
            courses: [{
                id: 0,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 1,
                courseListing: "EECS 16A",
                courseFullName: "Designing Information Devices and Systems",
                classNumber: "1",
                classDis: "105",
                classLab: "123",
            }, {
                id: 2,
                courseListing: "COMPSCI 61B",
                courseFullName: "Algorithms",
                classNumber: "13234",
                classDis: "1",
                classLab: "123",
            }, {
                id: 3,
                courseListing: "ANTHRO 2AC",
                courseFullName: "Introduction to Archaeology",
                classNumber: "13234",
                classDis: "105",
                classLab: "1",
            }, {
                id: 4,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 5,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 6,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 7,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 8,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 9,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }]
        },
        {
            id: 112,
            profileImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
            firstName: "Quentin",
            lastName: "Doe",
            email: "johndoe@example.com",
            password: "BadPassword123",
            pronouns: "He/Him",
            major: "Sociology",
            gradYear: "2026",
            userBio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            fbURL: "https://www.facebook.com/",
            igURL: "https://www.instagram.com/",
            scURL: "https://www.snapchat.com/en-US",
            courses: [{
                id: 0,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 1,
                courseListing: "EECS 16A",
                courseFullName: "Designing Information Devices and Systems",
                classNumber: "1",
                classDis: "105",
                classLab: "123",
            }, {
                id: 2,
                courseListing: "COMPSCI 61B",
                courseFullName: "Algorithms",
                classNumber: "13234",
                classDis: "1",
                classLab: "123",
            }, {
                id: 3,
                courseListing: "ANTHRO 2AC",
                courseFullName: "Introduction to Archaeology",
                classNumber: "13234",
                classDis: "105",
                classLab: "1",
            }, {
                id: 4,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 5,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 6,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 7,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 8,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 9,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }]
        },
        {
            id: 113,
            profileImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
            firstName: "Humphrey",
            lastName: "Doe",
            email: "johndoe@example.com",
            password: "BadPassword123",
            pronouns: "He/Him",
            major: "Sociology",
            gradYear: "2026",
            userBio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            fbURL: "https://www.facebook.com/",
            igURL: "https://www.instagram.com/",
            scURL: "https://www.snapchat.com/en-US",
            courses: [{
                id: 0,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 1,
                courseListing: "EECS 16A",
                courseFullName: "Designing Information Devices and Systems",
                classNumber: "1",
                classDis: "105",
                classLab: "123",
            }, {
                id: 2,
                courseListing: "COMPSCI 61B",
                courseFullName: "Algorithms",
                classNumber: "13234",
                classDis: "1",
                classLab: "123",
            }, {
                id: 3,
                courseListing: "ANTHRO 2AC",
                courseFullName: "Introduction to Archaeology",
                classNumber: "13234",
                classDis: "105",
                classLab: "1",
            }, {
                id: 4,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 5,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 6,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 7,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 8,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 9,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }]
        },
        {
            id: 114,
            profileImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
            firstName: "Frank",
            lastName: "Doe",
            email: "johndoe@example.com",
            password: "BadPassword123",
            pronouns: "He/Him",
            major: "Sociology",
            gradYear: "2026",
            userBio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            fbURL: "https://www.facebook.com/",
            igURL: "https://www.instagram.com/",
            scURL: "https://www.snapchat.com/en-US",
            courses: [{
                id: 0,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 1,
                courseListing: "EECS 16A",
                courseFullName: "Designing Information Devices and Systems",
                classNumber: "1",
                classDis: "105",
                classLab: "123",
            }, {
                id: 2,
                courseListing: "COMPSCI 61B",
                courseFullName: "Algorithms",
                classNumber: "13234",
                classDis: "1",
                classLab: "123",
            }, {
                id: 3,
                courseListing: "ANTHRO 2AC",
                courseFullName: "Introduction to Archaeology",
                classNumber: "13234",
                classDis: "105",
                classLab: "1",
            }, {
                id: 4,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 5,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 6,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 7,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 8,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 9,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }]
        },
        {
            id: 115,
            profileImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
            firstName: "Sam",
            lastName: "Doe",
            email: "johndoe@example.com",
            password: "BadPassword123",
            pronouns: "He/Him",
            major: "Sociology",
            gradYear: "2026",
            userBio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            fbURL: "https://www.facebook.com/",
            igURL: "https://www.instagram.com/",
            scURL: "https://www.snapchat.com/en-US",
            courses: [{
                id: 0,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 1,
                courseListing: "EECS 16A",
                courseFullName: "Designing Information Devices and Systems",
                classNumber: "1",
                classDis: "105",
                classLab: "123",
            }, {
                id: 2,
                courseListing: "COMPSCI 61B",
                courseFullName: "Algorithms",
                classNumber: "13234",
                classDis: "1",
                classLab: "123",
            }, {
                id: 3,
                courseListing: "ANTHRO 2AC",
                courseFullName: "Introduction to Archaeology",
                classNumber: "13234",
                classDis: "105",
                classLab: "1",
            }, {
                id: 4,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 5,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 6,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 7,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 8,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 9,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }]
        },
        {
            id: 116,
            profileImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
            firstName: "Nathan",
            lastName: "Doe",
            email: "johndoe@example.com",
            password: "BadPassword123",
            pronouns: "He/Him",
            major: "Sociology",
            gradYear: "2026",
            userBio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            fbURL: "https://www.facebook.com/",
            igURL: "https://www.instagram.com/",
            scURL: "https://www.snapchat.com/en-US",
            courses: [{
                id: 0,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 1,
                courseListing: "EECS 16A",
                courseFullName: "Designing Information Devices and Systems",
                classNumber: "1",
                classDis: "105",
                classLab: "123",
            }, {
                id: 2,
                courseListing: "COMPSCI 61B",
                courseFullName: "Algorithms",
                classNumber: "13234",
                classDis: "1",
                classLab: "123",
            }, {
                id: 3,
                courseListing: "ANTHRO 2AC",
                courseFullName: "Introduction to Archaeology",
                classNumber: "13234",
                classDis: "105",
                classLab: "1",
            }, {
                id: 4,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 5,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 6,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 7,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 8,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 9,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }]
        },
        {
            id: 117,
            profileImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
            firstName: "Extra",
            lastName: "Doe",
            email: "johndoe@example.com",
            password: "BadPassword123",
            pronouns: "He/Him",
            major: "Sociology",
            gradYear: "2026",
            userBio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            fbURL: "https://www.facebook.com/",
            igURL: "https://www.instagram.com/",
            scURL: "https://www.snapchat.com/en-US",
            courses: [{
                id: 0,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 1,
                courseListing: "EECS 16A",
                courseFullName: "Designing Information Devices and Systems",
                classNumber: "1",
                classDis: "105",
                classLab: "123",
            }, {
                id: 2,
                courseListing: "COMPSCI 61B",
                courseFullName: "Algorithms",
                classNumber: "13234",
                classDis: "1",
                classLab: "123",
            }, {
                id: 3,
                courseListing: "ANTHRO 2AC",
                courseFullName: "Introduction to Archaeology",
                classNumber: "13234",
                classDis: "105",
                classLab: "1",
            }, {
                id: 4,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 5,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 6,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 7,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 8,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }, {
                id: 9,
                courseListing: "COMPSCI 61A",
                courseFullName: "Introduction to Progamming and Program Design and Pretty Much Everything Programming",
                classNumber: "13234",
                classDis: "105",
                classLab: "123",
            }]
        },
    ]
}


export default placeHolderData;